# Generated by Django 3.2 on 2021-12-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.CharField(max_length=300, primary_key=True, serialize=False),
                ),
                ("display_name", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
                ("picture", models.CharField(max_length=300)),
            ],
        ),
    ]
