# Generated by Django 3.2 on 2022-02-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_stuff",
            field=models.BooleanField(default=False),
        ),
    ]
