version: "3"
services:
  backend:
    env_file:
      - .env
    build: .
    volumes:
      - .:/backend
    tty: true
    working_dir: /backend
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
