# Generated by Django 3.2 on 2021-11-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('stage_index', models.IntegerField()),
                ('rule', models.CharField(max_length=300)),
            ],
        ),
    ]
