# Generated by Django 3.2 on 2022-02-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('objective', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('index', models.IntegerField()),
            ],
        ),
    ]
