# Generated by Django 3.2 on 2022-02-08 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stage_api", "0004_stage_movie_url"),
        ("step_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="stage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="stage_api.stage",
            ),
            preserve_default=False,
        ),
    ]
