# Generated by Django 3.2 on 2022-05-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("step_api", "0002_stepcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="option",
            field=models.JSONField(default={}),
        ),
    ]
