# Generated by Django 3.2 on 2022-05-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_api", "0001_initial"),
        ("step_api", "0003_step_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="step",
            name="opponents",
            field=models.ManyToManyField(related_name="opponents", to="code_api.Code"),
        ),
        migrations.DeleteModel(
            name="StepCode",
        ),
    ]
