# Generated by Django 3.2 on 2022-06-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("code_api", "0001_initial"),
        ("step_api", "0004_auto_20220508_1754"),
    ]

    operations = [
        migrations.AlterField(
            model_name="step",
            name="opponents",
            field=models.ManyToManyField(
                blank=True, default=[], related_name="opponents", to="code_api.Code"
            ),
        ),
        migrations.AlterField(
            model_name="step",
            name="option",
            field=models.JSONField(blank=True, default={}),
        ),
    ]
