# Generated by Django 3.2 on 2022-06-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("step_api", "0005_auto_20220602_1451"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="step",
            name="description",
        ),
    ]
