# Generated by Django 3.2 on 2021-12-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("stage_index", models.IntegerField()),
                ("objective", models.CharField(max_length=300)),
                ("movie_url", models.URLField()),
            ],
        ),
    ]
