# Generated by Django 3.2 on 2022-01-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("world_api", "0001_initial"),
        ("stage_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stage",
            old_name="rule",
            new_name="objective",
        ),
        migrations.RemoveField(
            model_name="stage",
            name="name",
        ),
        migrations.AddField(
            model_name="stage",
            name="world",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="world_api.world",
            ),
            preserve_default=False,
        ),
    ]
