# Generated by Django 3.2 on 2022-01-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stage_api", "0002_auto_20220127_0210"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stage",
            old_name="stage_index",
            new_name="index",
        ),
    ]
