# Generated by Django 3.2 on 2022-01-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stage_api", "0003_rename_stage_index_stage_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="movie_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
